# -*- coding: utf-8 -*-
"""student_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyXnOt2_pt68oeL8ls5NaXIQ8zGQszE7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/student-mat.csv', sep=';')

print(df.head())

print(df.shape)
print(df.info())

print(df.isnull().sum())

df = df.drop_duplicates()
print("Duplicates removed")
print(df.shape)

avg_grade = df['G3'].mean()
print("Average Final Grade:", avg_grade)

high_scorers = df[df['G3'] > 15]
print("Students scoring above 15:", len(high_scorers))

correlation = df['studytime'].corr(df['G3'])
print("Correlation:", correlation)

gender_avg = df.groupby('sex')['G3'].mean()
print(gender_avg)

plt.hist(df['G3'])
plt.title("Distribution of Final Grades")
plt.xlabel("Grades")
plt.ylabel("Frequency")
plt.show()

plt.scatter(df['studytime'], df['G3'])
plt.title("Study Time vs Final Grade")
plt.xlabel("Study Time")
plt.ylabel("Final Grade")
plt.show()

gender_avg.plot(kind='bar')
plt.title("Average Grade by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Grade")
plt.show()